query {
    markets {
        items {
            uniqueKey
            lltv
            oracleAddress
            irmAddress
            loanAsset {
                address
                symbol
                decimals
            }
            collateralAsset {
                address
                symbol
                decimals
            }
            state {
                borrowApy
                borrowAssets
                borrowAssetsUsd
                supplyApy
                supplyAssets
                supplyAssetsUsd
                fee
                utilization
            }
        }
    }
}
